name: casamod-zimaos

services:
  casamod-zimaos-api:
    image: flaviusgheorghe/casamod-zimaos-api:${CASAMOD_VERSION:-latest}
    container_name: casamod-zimaos-api
    network_mode: host
    restart: unless-stopped
    environment:
      DATA_DIR: /data
      PORT: "8090"
    volumes:
      - /DATA/AppData/casamod:/data

  casamod-zimaos-proxy:
    image: flaviusgheorghe/casamod-zimaos-proxy:${CASAMOD_VERSION:-latest}
    container_name: casamod-zimaos-proxy
    network_mode: host
    restart: unless-stopped
    depends_on:
      - casamod-zimaos-api
    volumes:
      - /DATA/AppData/casamod/mod:/mods:ro
